### ISSUE TITLE
Feature Request - Accounting Module 

### ISSUE THREAD

**Issue by maxiewright** [Maxiewright/orms#4]
Create an accounting module to maintain simple income and expenditure statements for funds/accounts. 

```[Tasklist]

### Tasks

- [ ] Add the ability to manage multiple funds/accounts 
- [ ] Have printable receipts of monies issued/received 
- [ ] Add the ability to upload expenditure receipts to ensure accountability
